#!/bin/bash

set -euo pipefail
# Load environment so "module" command works
if [ -f /etc/profile.d/modules.sh ]; then
    source /etc/profile.d/modules.sh
fi
module purge
module load miniconda/pytorch-tensorflow-gpu

# source "$(conda info --base)/etc/profile.d/conda.sh"
# conda activate buildrust

python -m pip install --user tqdm
python -m pip install --user PyYAML
python -m pip install --user matplotlib
python -m pip install --user seaborn


export PYTHONUNBUFFERED=1

# Echo git branch and commit information
echo "Git Branch: $(git rev-parse --abbrev-ref HEAD)"
echo "Git Commit: $(git rev-parse HEAD)"
echo "Git Commit (short): $(git rev-parse --short HEAD)"


# Get number of GPUs available
NUM_GPUS=$(nvidia-smi --query-gpu=name --format=csv,noheader | wc -l)
echo "Number of GPUs detected: $NUM_GPUS"
export USE_OPENMP=1
cd VQVAE
python -u compare_different_models.py 


# Echo git branch and commit information
echo "Git Branch: $(git rev-parse --abbrev-ref HEAD)"
echo "Git Commit: $(git rev-parse HEAD)"
echo "Git Commit (short): $(git rev-parse --short HEAD)"


