#!/bin/bash

set -euo pipefail
# Load environment so "module" command works
if [ -f /etc/profile.d/modules.sh ]; then
    source /etc/profile.d/modules.sh
fi
module purge
module load miniconda/pytorch-tensorflow-gpu

export PYTHONUNBUFFERED=1
# Echo git branch and commit information
echo "Git Branch: $(git rev-parse --abbrev-ref HEAD)"
echo "Git Commit: $(git rev-parse HEAD)"
echo "Git Commit (short): $(git rev-parse --short HEAD)"

# Get number of GPUs available
NUM_GPUS=$(nvidia-smi --query-gpu=name --format=csv,noheader | wc -l)
echo "Number of GPUs detected: $NUM_GPUS"


python reconstruct_encoded_df.py --config "$CONFIG" --vqvae_config "$VQ_CONFIG"
echo "going for visualization"
python vis_original_vs_reconstructed.py --config "$CONFIG" --vqvae_config "$VQ_CONFIG"
echo "done visualizing"

