#!/bin/bash

set -euo pipefail
# Load environment so "module" command works
if [ -f /etc/profile.d/modules.sh ]; then
    source /etc/profile.d/modules.sh
fi
module purge
module load miniconda/pytorch-tensorflow-gpu
module list
python -c "import torch; print('PyTorch version:', torch.__version__)"


python -m pip install --user wandb
export WANDB_API_KEY=$(cat ~/.wandb_key)
echo "Config argument: $CONFIG"

export PYTHONUNBUFFERED=1
# Echo git branch and commit information
echo "Git Branch: $(git rev-parse --abbrev-ref HEAD)"
echo "Git Commit: $(git rev-parse HEAD)"
echo "Git Commit (short): $(git rev-parse --short HEAD)"

# Get number of GPUs available
NUM_GPUS=$(nvidia-smi --query-gpu=name --format=csv,noheader | wc -l)
echo "Number of GPUs detected: $NUM_GPUS"

#Launch distributed training with torchrun if multiple GPUs, otherwise single GPU
if [ "$NUM_GPUS" -gt 1 ]; then
    echo "Launching distributed training on $NUM_GPUS GPUs"
    torchrun --standalone --nproc_per_node=$NUM_GPUS train.py --config "$CONFIG"
else
    echo "Launching single GPU training"
    python -u encoded_train.py --config "$CONFIG"
fi
# Echo git branch and commit information
echo "Git Branch: $(git rev-parse --abbrev-ref HEAD)"
echo "Git Commit: $(git rev-parse HEAD)"
echo "Git Commit (short): $(git rev-parse --short HEAD)"


python encoded_sample.py --config "$CONFIG"
echo "last step"
python encoded_visualizer.py --config "$CONFIG"

