#!/bin/bash

set -euo pipefail

module purge
module load miniconda/pytorch-tensorflow-gpu-2024.09

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate buildrust
python -m pip install --user tiktoken
python -m pip install --user seaborn
python -m pip install --user wandb==0.15.11
export WANDB_API_KEY=$(cat ~/.wandb_key)
python sample.py --ckpt_path "/home/sbaghernezha/projects/chatemg/chatemg/scripts/models/train-emg-allsubjects-2khz_gpu-a9-n006_2025-10-26_23-05-21/iter_30000_train_0.0451245_val_0.0453732"
