#!/bin/bash

set -euo pipefail
# Load environment so "module" command works
if [ -f /etc/profile.d/modules.sh ]; then
    source /etc/profile.d/modules.sh
fi
module purge
module load miniconda/pytorch-tensorflow-gpu-2024.09

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate buildrust
python -m pip install --user tqdm
python -c "import sklearn; print(f'scikit-learn version: {sklearn.__version__}')"

export PYTHONUNBUFFERED=1

# Echo git branch and commit information
echo "Git Branch: $(git rev-parse --abbrev-ref HEAD)"
echo "Git Commit: $(git rev-parse HEAD)"
echo "Git Commit (short): $(git rev-parse --short HEAD)"

# Get number of GPUs available
NUM_GPUS=$(nvidia-smi --query-gpu=name --format=csv,noheader | wc -l)
echo "Number of GPUs detected: $NUM_GPUS"


cd VQVAE
python -u pipeline.py


# Echo git branch and commit information
echo "Git Branch: $(git rev-parse --abbrev-ref HEAD)"
echo "Git Commit: $(git rev-parse HEAD)"
echo "Git Commit (short): $(git rev-parse --short HEAD)"


