name: "run1_512_512_100epoch"
number_of_epochs: 100
input_dim: 8         
hidden_dim: 512    
codebook_size: 512
code_dim: 512
window_size: 300    
stride : 150  
lambda_loss: 0.01  # Increased to provide stronger embedding loss signal     
batch_size: 64
learning_rate: 1e-4
decay: 0.99           



participants_list_ids : ["033106b27b","bc4dd952fe","31afab1e30","97c6aaac2d","7037a93026","98aa5fac2d","ecfa481b42","e49db6578f","27f6898a3f","3f858df9cf","9780ed81f4"] #"bc4dd952fe","31afab1e30","97c6aaac2d","7037a93026","98aa5fac2d"]
sensor_type : "emg"
axis : "x"
location : "forearm" 

raw_data_path : "/home/sbaghernezha/data/"
df_raw_name : "final_df.csv"
converted_data_path: "/home/sbaghernezha/projects/chatemg/chatemg/data_for_vqvae/"

